//
// Generated file, do not edit! Created by opp_msgtool 6.0 from msgtype.msg.
//

#ifndef __MSGTYPE_M_H
#define __MSGTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Message;
/**
 * Class generated from <tt>msgtype.msg:9</tt> by opp_msgtool.
 * <pre>
 * message Message
 * {
 *     int sender_id;
 *     int l_id;
 *     int l_clock;
 *     string text;
 *     int mex_type;
 * }
 * </pre>
 */
class Message : public ::omnetpp::cMessage
{
  protected:
    int sender_id = 0;
    int l_id = 0;
    int l_clock = 0;
    omnetpp::opp_string text;
    int mex_type = 0;

  private:
    void copy(const Message& other);

  protected:
    bool operator==(const Message&) = delete;

  public:
    Message(const char *name=nullptr, short kind=0);
    Message(const Message& other);
    virtual ~Message();
    Message& operator=(const Message& other);
    virtual Message *dup() const override {return new Message(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSender_id() const;
    virtual void setSender_id(int sender_id);

    virtual int getL_id() const;
    virtual void setL_id(int l_id);

    virtual int getL_clock() const;
    virtual void setL_clock(int l_clock);

    virtual const char * getText() const;
    virtual void setText(const char * text);

    virtual int getMex_type() const;
    virtual void setMex_type(int mex_type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Message& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Message& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Message *fromAnyPtr(any_ptr ptr) { return check_and_cast<Message*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MSGTYPE_M_H

